# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path
import sys

block_cipher = None

BASE_DIR = Path.cwd()

datas = [
    (str(BASE_DIR / 'frontend' / 'dist'), 'frontend/dist'),
    (str(BASE_DIR / 'Mapping' / 'AA_to_PowerAutomate_Action_Mapping.xlsx'), 'Mapping'),
]

hiddenimports = [
    'uvicorn',
    'uvicorn.logging',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.lifespan',
    'uvicorn.lifespan.on',
    'uvicorn.lifespan.off',
    'fastapi',
    'fastapi.staticfiles',
    'fastapi.responses',
    'fastapi.middleware.cors',
    'starlette',
    'starlette.staticfiles',
    'starlette.routing',
    'pydantic',
    'sqlalchemy',
    'sqlalchemy.dialects.sqlite',
    'openpyxl',
    'openpyxl.cell._writer',
    'multipart',
    'python_multipart',
    'backend',
    'backend.app',
    'backend.db',
    'backend.db.database',
    'backend.db.models',
    'backend.utils',
    'backend.utils.paths',
    'backend.utils.logger',
    'backend.utils.security',
    'backend.ai.explainer',
    'backend.migration.centricity_analyzer',
    'backend.migration.classifier',
    'backend.migration.cloud_rules',
    'backend.migration.desktop_rules',
    'backend.migration.hybrid_rules',
    'backend.migration.mapping_engine',
    'backend.migration.migration_plan',
    'backend.migration.excel_mapping_db',
    'backend.services.a360_preprocessor',
    'backend.services.a360_parser',
    'backend.services.task_analyzer',
    'backend.services.variable_analyzer',
    'backend.services.dependency_analyzer',
    'backend.services.report_generator',
    'backend.services.pipeline_orchestrator',
    'backend.services.code_generator',
    'backend.api.upload',
    'backend.api.analysis',
    'backend.api.workflows',
    'backend.api.actions',
    'backend.api.variables',
    'backend.api.disabled_actions',
    'backend.api.tasks',
    'backend.api.migration',
    'backend.api.reports',
    'backend.api.search',
    'backend.api.codegen',
]

a = Analysis(
    ['desktop_launcher.py'],
    pathex=[str(BASE_DIR)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'scipy'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='A360_to_PowerAutomate_Migration_Analyzer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
